FROM maven:3.8.5-openjdk-17 AS mvn

ADD . $MAVEN_HOME

RUN cd $MAVEN_HOME \
 && mvn -B -U clean package -DskipTests=false \
 && cp -r target/$(ls target | grep "\-dist$" | head -1) /dist


FROM norstella/oxalis:latest-17

COPY --from=mvn /dist /oxalis/ext
