name: Oxalis-AS4 Master Build

on:
  push:
    branches-ignore:
      - feature/java-17

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B --no-transfer-progress  package --file pom.xml
